// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// hello_world
void hello_world();
RcppExport SEXP implicit_hello_world() {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        hello_world();
    }
    return R_NilValue;
END_RCPP
}
// test
arma::mat test(arma::mat input1);
RcppExport SEXP implicit_test(SEXP input1SEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< arma::mat >::type input1(input1SEXP );
        arma::mat __result = test(input1);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// run_online_algorithm
Rcpp::List run_online_algorithm(SEXP dataset, SEXP experiment, SEXP algorithm, SEXP verbose);
RcppExport SEXP implicit_run_online_algorithm(SEXP datasetSEXP, SEXP experimentSEXP, SEXP algorithmSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type dataset(datasetSEXP );
        Rcpp::traits::input_parameter< SEXP >::type experiment(experimentSEXP );
        Rcpp::traits::input_parameter< SEXP >::type algorithm(algorithmSEXP );
        Rcpp::traits::input_parameter< SEXP >::type verbose(verboseSEXP );
        Rcpp::List __result = run_online_algorithm(dataset, experiment, algorithm, verbose);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
