# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hello_world <- function() {
    invisible(.Call('implicit_hello_world', PACKAGE = 'implicit'))
}

rcpparma_outerproduct <- function(x) {
    .Call('implicit_rcpparma_outerproduct', PACKAGE = 'implicit', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('implicit_rcpparma_innerproduct', PACKAGE = 'implicit', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('implicit_rcpparma_bothproducts', PACKAGE = 'implicit', x)
}

