# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hello_world <- function() {
    invisible(.Call('implicit_hello_world', PACKAGE = 'implicit'))
}

test <- function(input1) {
    .Call('implicit_test', PACKAGE = 'implicit', input1)
}

run_online_algorithm <- function(dataset, experiment, algorithm, verbose) {
    .Call('implicit_run_online_algorithm', PACKAGE = 'implicit', dataset, experiment, algorithm, verbose)
}

